# Generated by Django 5.1.1 on 2024-09-26 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='views',
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
