# Generated by Django 5.1.1 on 2024-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_views_recipe_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
