# Generated by Django 4.2.8 on 2024-10-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
