# Generated by Django 4.2.8 on 2024-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Chinese', 'Chinese'), ('American', 'American'), ('Filipino', 'Filipino'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Indian', 'Indian'), ('Japanese', 'Japanese')], max_length=100, null=True),
        ),
    ]
