# Generated by Django 5.1.1 on 2024-10-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_usercategoryinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategoryInteraction',
        ),
    ]
