# Generated by Django 5.1.1 on 2024-10-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_visitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitCount',
        ),
    ]
