# Generated by Django 5.1.1 on 2024-09-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
