# Generated by Django 5.1.1 on 2024-09-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_is_active_profile_is_admin_profile_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_id',
        ),
    ]
