# Generated by Django 5.1.1 on 2024-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_image'),
        ('recipes', '0021_categoryviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_views',
            field=models.ManyToManyField(through='recipes.CategoryViewCount', to='recipes.category'),
        ),
    ]
