# Generated by Django 5.1.1 on 2024-10-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_category_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category_views',
        ),
    ]
