# Generated by Django 5.1.1 on 2024-10-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_categoryviewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryViewCount',
        ),
    ]
